server:
  port: 8080

spring:
  application:
    name: interview-simulation-system
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://47.93.172.25:3306/interview?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: youruser
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 日志配置
logging:
  level:
    com.interview: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 跨域配置
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"

# 讯飞星火大模型配置
xunfei:
  spark:
    appid: "453afd9a"
    apiKey: "bc78b8908cb5c19f9429c8de0d07adfc"
    apiSecret: "MTQxMDM1YzhmYTc4OTg4Y2ExMDg1ZTZh"
    url: "https://spark-api-open.xf-yun.com/v1/chat/completions"
  iat:
    appid: "ce130cad"
    apiKey: "1a87ba822266e04b634cea830e9b9b8e"
    apiSecret: "NjQwNzgxMzI0ZWEwMmJmZWZmNmVkNThh"
    url: "https://iat-api.xfyun.cn/v2/iat"
# 面部情感识别API配置
facial:
  api:

    url: "https://api.facial-analysis.com/v1/analyze"

# 肢体语言识别API配置
body:
  api:
    key: "your_body_language_api_key"
    url: "https://api.body-language.com/v1/analyze" 