server:
  port: 8080

spring:
  application:
    name: interview-simulation-system
  
  # H2内存数据库配置（用于测试）
  datasource:
    url: jdbc:h2:mem:interview_system
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

# 日志配置
logging:
  level:
    com.interview: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 